I am facing below errors while trying to compile caffe with "CPU_ONLY := 1" flag. There is some error related to STUB_GPU macro. It leads to redefinition of all the functions which gives compiler error. Below is the screenshot attached: 

![image](https://user-images.githubusercontent.com/35452780/69619712-44687500-103c-11ea-9b83-73e0cbc90a85.png)

Hello!

I get the following error in the _cutoff_tile function:
deepcut-cnn/python/pose/estimate_pose.py in _cutoff_tile(sm, num_tiles, idx, cut_off, is_x)
    259         sm = sm[cut_off:, ...]
    260     else:
--> 261         sm = sm[cut_off:-cut_off, ...]
    262     if is_x:
    263         sm = sm.transpose((1, 0, 2, 3))

TypeError: slice indices must be integers or None or have an __index__ method

From what I have seen in the estimate_pose.py file, 
cut_off = rf / stride 
and rf = 224 and _STRIDE = 8. (with the . (dot)), so cut_off is indeed a float number. I tried to change this, but then it does not work correctly.

And this does not happen with all the pictures, and I couldn't find a pattern in the picture where it does.
Any help?

Thank you!
Hello!

I would like to know what the minimum requirements on the os are, such as cpu, ram, graphics card...

Thanks!
Is there any possible way to train on my own dataset? Thank you!
ERROR:

calling solver: /home/yulijun/deepcut/external/solver/solver-callback /home/yulijun/deepcut/data//mpii-multiperson/multicut//problem-0002.h5  /home/yulijun/deepcut/data//mpii-multiperson/multicut//solution-0002.h5  m 86400
echo $HOSTNAME: Aborted
hostname: 

malloc: unknown:0: assertion botched

free: called with unallocated block argument
last command: (null)
Aborting...

malloc: unknown:0: assertion botched

free: called with unallocated block argument
last command: (null)
Aborting...export GRB_LICENSE_FILE=/home/yulijun/deepcut/data/gurobi.lic; /home/yulijun/deepcut/external/solver/solver-callback /home/yulijun/deepcut/data//mpii-multiperson/multicut//problem-0002.h5  /home/yulijun/deepcut/data//mpii-multiperson/multicut//solution-0002.h5  m 86400: Aborted
Elapsed time is 0.099782 seconds.
Error using test_spatial_app_neighbour (line 444)
solver error

Error in demo_multiperson (line 12)
test_spatial_app_neighbour(experiment_index, image_index, 1, true, true);


hope you give me some advice!
Hiï¼ŒI want to use the evaluation script evaluateAP.m downloaded on MPII Human Pose Dataset to measure my model's performance, but I could not find the annolist_dataset_v12.mat file loaded in this line of the script.
```
load([p.gtDir '/annolist_dataset_v12'],'annolist');
```
Do you know how to get this file, thanks.


Hi,I try to drop the net resolution to raise the fps. and then I use the MPII Human Pose Dataset mentioned in your article to check out how much the map drop.On the Website:
http://human-pose.mpi-inf.mpg.de/#evaluation I mess around by the README.
```
pos = zeros(length(rect),2);
for ridx = 1:length(rect)
    pos(ridx,:) = [rect(ridx).objpos.x rect(ridx).objpos.y];
end
x1 = min(pos(:,1)); y1 = min(pos(:,2)); x2 = max(pos(:,1)); y2 = max(pos(:,2));
```
where can I get the rect ?
```
load('groups_v12.mat','groups');
[imgidxs_multi_test,rectidxs_multi_test] = getMultiPersonGroups(groups,RELEASE,false);
```
what is the groups_v12.mat ?
I search on the web for a day, and get little effective information. can you give me some suggestion ? thx
After successfully installing Gurobi 6.0.5 I try to make the solver. During linking I get the following:

CMakeFiles/solver-callback.dir/src/pose/research/solver-callback.cxx.o: In function `void andres::ilp::Gurobi<double>::addConstraint<unsigned long*, double const*>(unsigned long*, unsigned long*, double const*, double, double) [clone .constprop.252]':
solver-callback.cxx:(.text+0x2fc): undefined reference to`GRBModel::addConstr(GRBLinExpr const&, char, GRBLinExpr const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
solver-callback.cxx:(.text+0x363): undefined reference to `GRBModel::addConstr(GRBLinExpr const&, char, GRBLinExpr const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
CMakeFiles/solver-callback.dir/src/pose/research/solver-callback.cxx.o: In function`andres::ilp::Gurobi<double>::Callback::callback()':
solver-callback.cxx:(.text._ZN6andres3ilp6GurobiIdE8Callback8callbackEv[_ZN6andres3ilp6GurobiIdE8Callback8callbackEv]+0xbf): undefined reference to `GRBException::getMessage[abi:cxx11]() const'
CMakeFiles/solver-callback.dir/src/pose/research/solver-callback.cxx.o: In function`void andres::ilp::Gurobi<double>::addConstraint<__gnu_cxx::__normal_iterator<unsigned long*, std::vector<unsigned long, std::allocator<unsigned long> > >, __gnu_cxx::__normal_iterator<double*, std::vector<double, std::allocator<double> > > >(__gnu_cxx::__normal_iterator<unsigned long*, std::vector<unsigned long, std::allocator<unsigned long> > >, __gnu_cxx::__normal_iterator<unsigned long*, std::vector<unsigned long, std::allocator<unsigned long> > >, __gnu_cxx::__normal_iterator<double*, std::vector<double, std::allocator<double> > >, double, double) [clone .constprop.251]':
solver-callback.cxx:(.text._ZN6andres3ilp6GurobiIdE13addConstraintIN9__gnu_cxx17__normal_iteratorIPmSt6vectorImSaImEEEENS5_IPdS7_IdSaIdEEEEEEvT_SF_T0_dd.constprop.251[_ZN4pose13PoseEstimatorIN6andres3ilp6GurobiIdEE24FeasibleSolutionCallbackE25addAllCouplingConstraintsEv]+0xb2): undefined reference to `GRBModel::addConstr(GRBLinExpr const&, char, GRBLinExpr const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
CMakeFiles/solver-callback.dir/src/pose/research/solver-callback.cxx.o: In function`void andres::ilp::Gurobi<double>::addConstraint<unsigned long*, double const*>(unsigned long_, unsigned long_, double const_, double, double) [clone .constprop.253]':
solver-callback.cxx:(.text._ZN6andres3ilp6GurobiIdE13addConstraintIPmPKdEEvT_S7_T0_dd.constprop.253[_ZN4pose13PoseEstimatorIN6andres3ilp6GurobiIdEE24FeasibleSolutionCallbackE36addAllImpossiblePartClassConstraintsEv]+0xb3): undefined reference to `GRBModel::addConstr(GRBLinExpr const&, char, GRBLinExpr const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
CMakeFiles/solver-callback.dir/src/pose/research/solver-callback.cxx.o: In function`void andres::ilp::Gurobi<double>::addConstraint<unsigned long_, double const_>(unsigned long_, unsigned long_, double const_, double, double)':
solver-callback.cxx:(.text._ZN6andres3ilp6GurobiIdE13addConstraintIPmPKdEEvT_S7_T0_dd[_ZN6andres3ilp6GurobiIdE13addConstraintIPmPKdEEvT_S7_T0_dd]+0x13c): undefined reference to `GRBModel::addConstr(GRBLinExpr const&, char, GRBLinExpr const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
solver-callback.cxx:(.text._ZN6andres3ilp6GurobiIdE13addConstraintIPmPKdEEvT_S7_T0_dd[_ZN6andres3ilp6GurobiIdE13addConstraintIPmPKdEEvT_S7_T0_dd]+0x19f): undefined reference to`GRBModel::addConstr(GRBLinExpr const&, char, GRBLinExpr const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
solver-callback.cxx:(.text._ZN6andres3ilp6GurobiIdE13addConstraintIPmPKdEEvT_S7_T0_dd[_ZN6andres3ilp6GurobiIdE13addConstraintIPmPKdEEvT_S7_T0_dd]+0x1f3): undefined reference to `GRBModel::addConstr(GRBLinExpr const&, char, GRBLinExpr const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
CMakeFiles/solver-callback.dir/src/pose/research/solver-callback.cxx.o:solver-callback.cxx:(.text._ZN6andres3ilp6GurobiIdE13addConstraintIN9__gnu_cxx17__normal_iteratorIPmSt6vectorImSaImEEEENS5_IPKmS9_EEEEvT_SE_T0_dd[_ZN6andres3ilp6GurobiIdE13addConstraintIN9__gnu_cxx17__normal_iteratorIPmSt6vectorImSaImEEEENS5_IPKmS9_EEEEvT_SE_T0_dd]+0x169): more undefined references to`GRBModel::addConstr(GRBLinExpr const&, char, GRBLinExpr const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)' follow
CMakeFiles/solver-callback.dir/src/pose/research/solver-callback.cxx.o: In function `main':
solver-callback.cxx:(.text.startup+0x5f9): undefined reference to`GRBException::getMessage[abi:cxx11]() const'
collect2: error: ld returned 1 exit status
CMakeFiles/solver-callback.dir/build.make:102: recipe for target 'solver-callback' failed
make[3]: **\* [solver-callback] Error 1
CMakeFiles/Makefile2:141: recipe for target 'CMakeFiles/solver-callback.dir/all' failed
make[2]: **\* [CMakeFiles/solver-callback.dir/all] Error 2
CMakeFiles/Makefile2:153: recipe for target 'CMakeFiles/solver-callback.dir/rule' failed
make[1]: **\* [CMakeFiles/solver-callback.dir/rule] Error 2
Makefile:155: recipe for target 'solver-callback' failed
make: **\* [solver-callback] Error 2

Gurobi environment set to:
GUROBI_HOME=/opt/gurobi605/linux64
LD_LIBRARY_PATH=/opt/gurobi605/linux64/lib

Output from CMake:
coert@beta039608 /mnt/33EE47FC4F4F9C75/Install/deepcut_multiperson/external/solver $ cmake . -DGUROBI_ROOT_DIR=/opt/gurobi605/linux64 -DGUROBI_VERSION=60
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp  
-- OpenMP found
-- Found HDF5: /usr/lib/x86_64-linux-gnu/hdf5/serial/lib/libhdf5.so;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/x86_64-linux-gnu/libsz.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libm.so (found version "1.8.16") 
-- Found GUROBI: /opt/gurobi605/linux64/lib/libgurobi60.so  
-- Found GLUT: /usr/lib/x86_64-linux-gnu/libglut.so  
-- Configuring done
-- Generating done
-- Build files have been written to: /mnt/33EE47FC4F4F9C75/Install/deepcut_multiperson/external/solver

What am I missing here?

Could you please let me know the issue with my demo?

[error.txt](https://github.com/eldar/deepcut/files/532349/error.txt)
...
I1016 22:46:16.365223 24943 net.cpp:816] Ignoring source layer loss_loc
I1016 22:46:16.374922 24943 net.cpp:816] Ignoring source layer loss_next
save dir /gpfs/work/f/fuf111/deepcut/data/mpii-multiperson/scoremaps/test
testing from net file /gpfs/work/f/fuf111/deepcut/data/caffe-models/ResNet-101-mpii-multiperson.caffemodel
deepcut: test (MPII multiperson test) 2/1758
F1016 22:46:17.488354 24943 syncedmem.cpp:136] Cannot use GPU in CPU-only Caffe: check mode.
**\* Check failure stack trace: ***

Hello everyone,
I'm testing your code for a project and I'm getting some of the following errors when I run `demo_multiperson.m:` 

_(in the console)_
`F0923 15:47:45.735599  4029 syncedmem.cpp:56] Check failed: error == cudaSuccess (2 vs. 0)  out of memory
*** Check failure stack trace: ***
Killed`

_(in matlab)_
`Cleared 0 solvers and 0 stand-alone nets
save dir .../git/deepcut/data/mpii-multiperson/scoremaps/test
testing from net file /home/marco/Desktop/mauro-skeletal-tracker/git/deepcut/data/caffe-models/ResNet-101-mpii-multiperson.caffemodel
deepcut: test (MPII multiperson test) 2/1758`

with a Matlab crash.

My video card is an **NVidia GeForce GTX 760 Ti 2GB**.

I'm new to deep learning and Caffe, but I've read on the web that sometimes is possible to run tests on less memory capable graphics cards, as in my case, by changing some parameters (like the **batch-size**). Is that possible in deepcut? Where could I change those parameters in your code?
Thank you in advance!
