Added the method for Unblocking the ps1 files.
Expected behavior: Prompt should remain unchanged and reject the action entirely.
Actual behavior: Prompt prefix changes, despite the message of an env not existing.
Reproduce: Activate an env that you know exists. Then attempt to activate one that doesn't exist. 

I discovered by mistake that the bug exists when using a system I didn't setup. It doesn't appear to have changed any actual behavior, but the only way to correct the prompt is to deactivate and reactivate the desired target env.
Can you make the activate/deactivate work when the environment is in users app data folder like this "AppData\Local\conda\conda\envs\py36"?
When I activate, the active environment is not changed from "None". Here is my conda info:

       active environment : None
       user config file : C:\Users\micha\.condarc
       populated config files : C:\Users\micha\.condarc
          conda version : 4.5.4
    conda-build version : 3.10.5
         python version : 3.6.5.final.0
       base environment : C:\Users\micha\Anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\micha\Anaconda3\pkgs
                          C:\Users\micha\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\micha\Anaconda3\envs
                          C:\Users\micha\AppData\Local\conda\conda\envs
                          C:\Users\micha\.conda\envs
               platform : win-64
             user-agent : conda/4.5.4 requests/2.18.4 CPython/3.6.5 Windows/10 Windows/10.0.17134
          administrator : False
             netrc file : None
           offline mode : False


Thank you and I appreciate the help.

Hey, not sure but for me it fixed the issue that I had to add ".ps1" to the deactivate in order to make it works..
This does not work on Conda 4.3.25. Is there any workaround? 
According to [issue#2](https://github.com/Liquidmantis/PSCondaEnvs/issues/2), add one line that copy deactivate.ps1 to $condaEnvName\Scripts when run the activate.ps1 to solve the issue.
The process of trying to deactivate an env or activate a different one after activating the first one doesn't successfully complete. There are no errors that show up in the console, it just refuses to switch. 