Hey there. I am trying to do the following:
```js
const Nightmare = require('nightmare');
const nightmare = Nightmare({ show: false })
let url = "https://vivo.sx/5ec5b4cd00#k4zme0wz"
let source = await nightmare.goto(url)
                            .wait("source")
                            .evaluate(() => { document.querySelector("source").src; })
                            .end();
console.log(source);
```
however it just returns "null" all the time. I even tried setting "show" to true for the Nightmare Instance and setting the wait to 10000ms and then tried to open the DevTools manually inside the Electron Window and it works in there. But after the 10 Seconds the Window closes and it still returns null. How can I fix this?

Edit: Output when running with Debug Flag:
```
  nightmare queueing action "goto" for https://vivo.sx/5ec5b4cd00#k4zmswxw +17s
  nightmare queueing action "wait" +1ms
  nightmare queueing action "evaluate" +1ms
  nightmare running +1ms
  nightmare electron child process exited with code 0: success! +13s
```
Working on updating the DefinitelyTyped definitions for this and ran into trouble with the return not matching the documented signature
Similar to #1515, except their fix is not working for me.

I also tried `npm cache clean --force`, still to no avail.

```
uname -a
Linux hyperion 5.3.0-24-generic #26-Ubuntu SMP Thu Nov 14 01:33:18 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

node --version
v12.13.1

npm --version
6.13.2
```

The code I'm running is straight from the example:

```js
const Nightmare = require('nightmare')
const nightmare = Nightmare({ show: true })

nightmare
  .goto('https://duckduckgo.com')
  .type('#search_form_input_homepage', 'github nightmare')
  .click('#search_button_homepage')
  .wait('#r1-0 a.result__a')
  .evaluate(() => document.querySelector('#r1-0 a.result__a').href)
  .end()
  .then(console.log)
  .catch(error => {
    console.error('Search failed:', error)
  })
```

My package.json:

```json
{
...
  "dependencies": {
    "nightmare": "^3.0.2"
  }
}
```

I'd copy the output of what I've run but there simply is none. The command `node index.js` instantly finishes with no output and no error code. (`echo $?` returns `0`)
Here is my code snippet:                     
```
const SGLink = nightmare
                       .goto('https://www.stadiumgoods.com/catalogsearch/result/?q='+ json.Products[i].styleId)
                       .wait('.item')
                       .evaluate(() => document.querySelector('.item').innerHTML)
                       .end()
                       .then(response => {
                           const $ = cheerio.load(response);
                           console.log($('a').attr('href'));
                           return $('a').attr('href');
                       }).catch(err => {
                           console.log(err);
                       }); 
                       console.log(SGLink); 
                       shoe.resellLinks.stadiumGoods = SGLink;

```

This snippet is within a for loop that searches this website for every styleID and grabs the link to the first product. However, this process itself takes about 30 seconds to just grab one link. Is there any way of making this faster?

The snippet works fine outside of the loop when it runs once but once insert it within the loop, it's not able to grab any links for some reason. Here is my error code:

```
{ Error: Nothing responds to "goto"
    at EventEmitter.<anonymous> (/Users/dhruv/Sneaks-API/node_modules/nightmare/lib/ipc.js:138:19)
    at emitMany (events.js:147:13)
    at EventEmitter.emit (events.js:224:7)
    at process.<anonymous> (/Users/dhruv/Sneaks-API/node_modules/nightmare/lib/ipc.js:49:10)
    at emitTwo (events.js:126:13)
    at process.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9) code: -1 }



```
I seem to be running into an edge case issue. When I leave nightmare.js program running for several hours it would eventually stop working. As my program is running I log out which steps it's on. Eventually after several hours progress stops.

I would then kill the program and try to start it again, but same thing happens. The program gets stuck on running the nightmare.js module.

The only solution I've found was to restart my computer, after which the program seems to run fine again for another few hours.

Does any one have any suggestions on what I should do or look into to find out what might be wrong? Or what I can do narrow down the logs so I can share it with the community?

I tried adding "DEBUG=nightmare*" and I got the outputs, but it seems to continually try to start submitting to "queue" again, but there's no message about what's failing or any error messages.

MBP macOS Catalina
nightmare: 3.0.2
node: 10.15.4

I've also ran this on my ubuntu server, and the same thing happens.

`SyntaxError: Invalid regular expression: /(?<=data-userid=")\d+(?=")/: Invalid group`

They're part of the current JS spec and supported in both Chrome and Node: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp#Browser_compatibility

I may have to look into Puppeteer until they're supported in Nightmare. Consider this a feature request!
Hi!
I would like to test whether a specific alert is triggered after clicking a button. I know I can catch alert events with `.on('page',..)` but this will catch it even if it is called before clicking the button, or if it is triggered because of another interaction... in other words, it will catch no matter when the alert appears.

I was wondering how I could achieve that with nightmare. I thought a workaroud could be using a boolean variable and set it to true once the button has been clicked, and then, when catching the event, check if such variable had been set to true. However I don't think this is a good solution, it would be great if I could integrate it in a flow, something like:
```
.click("#thebutton")
.wait(alertraised)
.click("#otherbutton")
.wait(otheralertraised)
```

I hope I explained myself good enough

Thanks in advance!
**ERROR:**
Warning in ./node_modules/nightmare/lib/nightmare.js

  Critical dependency: the request of a dependency is an expression

 MOCHA  Testing...

 RUNTIME EXCEPTION  Exception occurred while loading your tests                                                                                                                                                                                 Error: Electron failed to install correctly, please delete node_modules/electron and try installing again

**Reproduce:**
Vue CLI Version: @vue/cli 4.0.5
```bash
vue create app # With unit testing and typescript support
cd app
yarn add nightmare @types/nightmare
```

```js
import { expect } from 'chai';
import Nightmare from 'nightmare';

const nightmare = new Nightmare({ show: true });
const url = 'https://google.com';

expect(nightmare.goto(url).url()).to.be(url);
```

**Trials:**
I have tried to add electron.
`yarn add electron`

I have tried removing all folders in node_modules which contain electron and then running `yarn install` again.

I have tried removing the entire node_modules folder and then running `yarn install`
Hii there,

I'm building an app to scrape things using angular and electron and needed to use Puppeteer (which didn't work so I came across Nightmare).
I installed Nightmare using the following command:
> npm install --save nightmare

then started using it like so:
```js
Nightmare = require('nightmare')
nightmare = this.Nightmare({ 
  show: true,
  electronPath: require('electron')
});
```

When I run the app (and it comes across these statements), I get an error: 
```
Error: Cannot find module 'D:\Code\9animedl\node_modules\electron\dist\resources\electron.asar\package.json'
```

What am I doing wrong and how can I solve it?
