更新依赖版本，修复一些python3下运行的问题。
Bumps [werkzeug](https://github.com/pallets/werkzeug) from 0.11.9 to 0.15.3.
<details>
<summary>Release notes</summary>

*Sourced from [werkzeug's releases](https://github.com/pallets/werkzeug/releases).*

> ## 0.15.3
> * Blog: https://palletsprojects.com/blog/werkzeug-0-15-3-released/
> * Changes: https://werkzeug.palletsprojects.com/en/0.15.x/changes/#version-0-15-3
> 
> 
> ## 0.15.2
> * Blog: https://palletsprojects.com/blog/werkzeug-0-15-2-released/
> * Changes: https://werkzeug.palletsprojects.com/en/0.15.x/changes/#version-0-15-2
> 
> ## 0.15.1
> * Blog: https://palletsprojects.com/blog/werkzeug-0-15-1-released/
> * Changes: https://werkzeug.palletsprojects.com/en/0.15.x/changes/
> 
> ## 0.15.0
> * Blog: https://palletsprojects.com/blog/werkzeug-0-15-0-released/
> * Changes: https://werkzeug.palletsprojects.com/en/0.15.x/changes/
> 
> ## 0.13
> [Read the announcement here.](https://www.palletsprojects.com/blog/werkzeug-013-released/)
> 
> [Read the full changelog.](http://werkzeug.pocoo.org/docs/latest/changes/#version-0-13)
> 
> Install from [PyPI](https://pypi.org/Werkzeug/0.13) with pip:
> 
> ```
> pip install -U Werkzeug
> ```
> 
</details>
<details>
<summary>Changelog</summary>

*Sourced from [werkzeug's changelog](https://github.com/pallets/werkzeug/blob/master/CHANGES.rst).*

> Version 0.15.3
> --------------
> 
> Released 2019-05-14
> 
> -   Properly handle multi-line header folding in development server in
>     Python 2.7. (:issue:`1080`)
> -   Restore the ``response`` argument to :exc:`~exceptions.Unauthorized`.
>     (:pr:`1527`)
> -   :exc:`~exceptions.Unauthorized` doesn't add the ``WWW-Authenticate``
>     header if ``www_authenticate`` is not given. (:issue:`1516`)
> -   The default URL converter correctly encodes bytes to string rather
>     than representing them with ``b''``. (:issue:`1502`)
> -   Fix the filename format string in
>     :class:`~middleware.profiler.ProfilerMiddleware` to correctly handle
>     float values. (:issue:`1511`)
> -   Update :class:`~middleware.lint.LintMiddleware` to work on Python 3.
>     (:issue:`1510`)
> -   The debugger detects cycles in chained exceptions and does not time
>     out in that case. (:issue:`1536`)
> -   When running the development server in Docker, the debugger security
>     pin is now unique per container.
> 
> 
> Version 0.15.2
> --------------
> 
> Released 2019-04-02
> 
> -   ``Rule`` code generation uses a filename that coverage will ignore.
>     The previous value, "generated", was causing coverage to fail.
>     (:issue:`1487`)
> -   The test client removes the cookie header if there are no persisted
>     cookies. This fixes an issue introduced in 0.15.0 where the cookies
>     from the original request were used for redirects, causing functions
>     such as logout to fail. (:issue:`1491`)
> -   The test client copies the environ before passing it to the app, to
>     prevent in-place modifications from affecting redirect requests.
>     (:issue:`1498`)
> -   The ``"werkzeug"`` logger only adds a handler if there is no handler
>     configured for its level in the logging chain. This avoids double
>     logging if other code configures logging first. (:issue:`1492`)
> 
> 
> Version 0.15.1
> --------------
> 
> Released 2019-03-21
> 
> -   :exc:`~exceptions.Unauthorized` takes ``description`` as the first
></tr></table> ... (truncated)
</details>
<details>
<summary>Commits</summary>

- [`9b1123a`](https://github.com/pallets/werkzeug/commit/9b1123a779e95b5c38ca911ce1329e87a3348a92) release version 0.15.3
- [`00bc43b`](https://github.com/pallets/werkzeug/commit/00bc43b1672e662e5e3b8cecd79e67fc968fa246) unique debugger pin in Docker containers
- [`2cbdf2b`](https://github.com/pallets/werkzeug/commit/2cbdf2b02273daccf85845b1e1569096e65ffe58) Merge pull request [#1542](https://github-redirect.dependabot.com/pallets/werkzeug/issues/1542) from asottile/exceptions_arent_always_hashable
- [`0e669f6`](https://github.com/pallets/werkzeug/commit/0e669f6be532801267d35de23c5f5237b8406d8a) Fix unhashable exception types
- [`bdc17e4`](https://github.com/pallets/werkzeug/commit/bdc17e4cd10bbb17449006cef385ec953a11fc36) Merge pull request [#1540](https://github-redirect.dependabot.com/pallets/werkzeug/issues/1540) from pallets/break-tb-cycle
- [`44e38c2`](https://github.com/pallets/werkzeug/commit/44e38c2985bcd3a7c17467bead901b8f36528f5f) break cycle in chained exceptions
- [`777500b`](https://github.com/pallets/werkzeug/commit/777500b64647ea47b21e52e5e113ba1d86014c05) Merge pull request [#1518](https://github-redirect.dependabot.com/pallets/werkzeug/issues/1518) from NiklasMM/fix/1510_lint-middleware-python3-compa...
- [`e00c7c2`](https://github.com/pallets/werkzeug/commit/e00c7c2cedcbcad3772e4522813c78bc9a860fbe) Make LintMiddleware Python 3 compatible and add tests
- [`d590cc7`](https://github.com/pallets/werkzeug/commit/d590cc7cf2fcb34ebc0783eb3c2913e8ce016ed8) Merge pull request [#1539](https://github-redirect.dependabot.com/pallets/werkzeug/issues/1539) from pallets/profiler-format
- [`0388fc9`](https://github.com/pallets/werkzeug/commit/0388fc95e696513bbefbde293f3f76cc482df8fa) update filename_format for ProfilerMiddleware.
- Additional commits viewable in [compare view](https://github.com/pallets/werkzeug/compare/0.11.9...0.15.3)
</details>
<br />

[![Dependabot compatibility score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=werkzeug&package-manager=pip&previous-version=0.11.9&new-version=0.15.3)](https://help.github.com/articles/configuring-automated-security-fixes)

Dependabot will resolve any conflicts with this PR as long as you don't alter it yourself. You can also trigger a rebase manually by commenting `@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot ignore this [patch|minor|major] version` will close this PR and stop Dependabot creating any more for this minor/major version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop Dependabot creating any more for this dependency (unless you reopen the PR or upgrade to it yourself)
- `@dependabot use these labels` will set the current labels as the default for future PRs for this repo and language
- `@dependabot use these reviewers` will set the current reviewers as the default for future PRs for this repo and language
- `@dependabot use these assignees` will set the current assignees as the default for future PRs for this repo and language
- `@dependabot use this milestone` will set the current milestone as the default for future PRs for this repo and language

You can disable automated security fix PRs for this repo from the [Security Alerts page](https://github.com/WhaleShark-Team/cobra/network/alerts).

</details>
### System and Python Environment

|Item|Tooltip|Value|
macos，python3.7

### Description

[Description of the bug or feature]
python3 cobra.py -t xxx/xxx

[13:57:43] [INFO] [REPORT] Report URL: ?sid=a84c91ceug9k
[13:57:43] [INFO] [CLI] Target directory: /Users/xxx/xxx/xxx/xxx-xxx
[13:57:43] [INFO] [DETECTION] [FRAMEWORK] Unknown Framework
[13:57:43] [INFO] [CLI] [STATISTIC] Language: php Framework: Unknown Framework
[13:57:43] [INFO] [CLI] [STATISTIC] Files: 415, Extensions:19, Consume: 0.022696999999999967
[13:57:44] [INFO] [PUSH] 18 CVE Rules
[13:57:45] [INFO] [PUSH] 95 Rules

程序一直在这里，等很久也没有输出
### System and Python Environment

|Item|Tooltip|Value|
|---|---|---|
|System|Linux localhost 3.10.0-327.4.5.el7.x86_64 #1 SMP Mon Jan 25 22:07:14 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux||
|Python|2.7.5||
|Cobra|`python cobra.py`||

### Description

[Description of the bug or feature]
[root@localhost cobra]# python cobra.py
Traceback (most recent call last):
  File "cobra.py", line 18, in <module>
    from cobra import main
  File "/home/yangyang_zhang/cobra/cobra/__init__.py", line 22, in <module>
    from . import cli, api, config
  File "/home/yangyang_zhang/cobra/cobra/api.py", line 27, in <module>
    from flask import Flask, request, render_template, Blueprint
  File "/usr/lib/python2.7/site-packages/flask/__init__.py", line 21, in <module>
    from .app import Flask, Request, Response
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 23, in <module>
    from werkzeug.routing import BuildError, Map, RequestRedirect, Rule
  File "/usr/lib/python2.7/site-packages/werkzeug/routing.py", line 948
    exec(code, globs, locs)
SyntaxError: unqualified exec is not allowed in function '_compile_builder' it contains a nested function with free variables

### System and Python Environment

|Item|Tooltip|Value|
|---|---|---|
|System|`uname -a`||
|Python|`python -V`||
|Cobra|`python cobra.py`||

### Description

[Description of the bug or feature]

### Steps to Reproduce
utils.py 文件  def target_directory
149                 if '/' in branch:
150                     target, branch = '{t}:{b}'.format(t=target, b=branch), 'master'

这个判断必要性在哪，为什么要替换成master，master 难道一定会存在吗 ？？？？target 替换之后会通不过re.match的正则校验从而出错

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]
JAVA语言识别为PHP
![image](https://user-images.githubusercontent.com/32186147/61772429-d6f5cf00-ae24-11e9-82d8-ca6fbdb6d739.png)

### System and Python Environment

|System|Linux localhost.localdomain 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux|
|Python|Python 2.7.5||
|Cobra|v2.0.0-alpha.5|
|Code|JAVA|

### Description

在扫描个别的源码项目时会抛出以下错误，且报错的都是固定的几个项目报错
`[16:02:11] [WARNING] Traceback (most recent call last):
  File "/root/cobra/cobra/detection.py", line 185, in project_information
    for root, dirs, filenames in os.walk(absolute_path):
  File "/usr/lib64/python2.7/os.py", line 294, in walk
    for x in walk(new_path, topdown, onerror, followlinks):
  File "/usr/lib64/python2.7/os.py", line 294, in walk
    for x in walk(new_path, topdown, onerror, followlinks):
  File "/usr/lib64/python2.7/os.py", line 294, in walk
    for x in walk(new_path, topdown, onerror, followlinks):
  File "/usr/lib64/python2.7/os.py", line 284, in walk
    if isdir(join(top, name)):
  File "/usr/lib64/python2.7/posixpath.py", line 80, in join
    path += '/' + b
UnicodeDecodeError: 'utf8' codec can't decode byte 0xbd in position 1: invalid start byte

[16:02:12] [WARNING] issue seems to be already reported and resolved. Please update to the latest version from official GitHub repository at 'https://github.com/WhaleShark-Team/cobra'
[16:02:12] [WARNING] Traceback (most recent call last):
  File "/root/cobra/cobra/__init__.py", line 110, in main
    cli.start(args.target, args.format, args.output, args.special_rules, a_sid, args.dels)
  File "/root/cobra/cobra/cli.py", line 82, in start
    main_framework = dt.framework
  File "/root/cobra/cobra/detection.py", line 82, in framework
    frame_name = self.dependency_scan(root)  # Based on the dependency analysis framework type
  File "/root/cobra/cobra/detection.py", line 102, in dependency_scan
    dependencies = Dependencies(self.target_directory)
  File "/root/cobra/cobra/dependencies.py", line 183, in __init__
    self.dependencies()
  File "/root/cobra/cobra/dependencies.py", line 186, in dependencies
    file_path, flag = self.find_file()
  File "/root/cobra/cobra/dependencies.py", line 207, in find_file
    for root, dirs, filenames in os.walk(self.directory):
  File "/usr/lib64/python2.7/os.py", line 294, in walk
    for x in walk(new_path, topdown, onerror, followlinks):
  File "/usr/lib64/python2.7/os.py", line 294, in walk
    for x in walk(new_path, topdown, onerror, followlinks):
  File "/usr/lib64/python2.7/os.py", line 294, in walk
    for x in walk(new_path, topdown, onerror, followlinks):
  File "/usr/lib64/python2.7/os.py", line 284, in walk
    if isdir(join(top, name)):
  File "/usr/lib64/python2.7/posixpath.py", line 80, in join
    path += '/' + b
UnicodeDecodeError: 'utf8' codec can't decode byte 0xbd in position 1: invalid start byte

Traceback (most recent call last):
  File "/root/cobra/cobra/config.py", line 70, in __init__
    value = self.config.get(self.level1, self.level2)
  File "/usr/lib64/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
NoSectionError: No section: 'hash'
[16:02:12] [CRITICAL] ./configs file configure failed. http://cobra.feei.cn/config
Error: No section: 'hash'
[16:02:12] [INFO] [HASH] Projects is modified`
### System and Python Environment

|Item|Tooltip|Value|
|---|---|---|
|System|`uname -a`||
|Python|`python -V`||
|Cobra|`python cobra.py`||

### Description
在/cobra/pickup.py文件的165行左右，如下

```
class Directory(object):
    def __init__(self, absolute_path):
        self.absolute_path = absolute_path

    file_sum = 0
    type_nums = {}
    result = {}
    file = []
```
其中
```
    file_sum = 0
    type_nums = {}
    result = {}
    file = []
```
这几个变量声明成全局变量导致多个项目的文件信息都加在了一起，文件数也越来越多，导致后面的识别语言和框架也出错。
修复建议，将上面几个变量放在初始化函数中，如下：

```
class Directory(object):
    def __init__(self, absolute_path):
        self.absolute_path = absolute_path
        self.file_sum = 0
        self.type_nums = {}
        self.result = {}
        self.file = []
```

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]
1. 修复在web端输入目录提示url不合法问题
规则
https://pastebin.com/cmhayQhx

漏洞代码
https://pastebin.com/ZDEHytFD

web网页正则匹配无问题
![image](https://user-images.githubusercontent.com/34776076/57443321-56d9b780-7280-11e9-825f-bdc08a6fd2c8.png)

https://xz.aliyun.com/t/5051
